import { machineType } from "../../types/machine";

export const machineList: machineType[] = [
  {
    name: "Computador A",
    type: "Desktop",
    model: "X1000",
    manufactureDate: "2023-01-15",
    serialNumber: "SN123456789",
    location: "Sala 101",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Impressora B",
    type: "Laser",
    model: "P2000",
    manufactureDate: "2022-07-20",
    serialNumber: "SN987654321",
    location: "Sala 102",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Laptop C",
    type: "Notebook",
    model: "L500",
    manufactureDate: "2023-03-10",
    serialNumber: "SN112233445",
    location: "Sala 103",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Projetor D",
    type: "Multimedia",
    model: "PJ700",
    manufactureDate: "2021-11-05",
    serialNumber: "SN556677889",
    location: "Sala de Reuniões",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Servidor E",
    type: "Rackmount",
    model: "SRX100",
    manufactureDate: "2022-02-28",
    serialNumber: "SN998877665",
    location: "Sala de Servidores",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Monitor F",
    type: "LCD",
    model: "M3000",
    manufactureDate: "2021-09-12",
    serialNumber: "SN223344556",
    location: "Sala 104",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Scanner G",
    type: "Flatbed",
    model: "SC200",
    manufactureDate: "2023-06-18",
    serialNumber: "SN778899001",
    location: "Sala 105",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Teclado H",
    type: "USB",
    model: "TK400",
    manufactureDate: "2023-05-25",
    serialNumber: "SN123456001",
    location: "Sala 106",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Mouse I",
    type: "Optical",
    model: "MS500",
    manufactureDate: "2023-04-15",
    serialNumber: "SN654321002",
    location: "Sala 107",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Telefone J",
    type: "IP",
    model: "T1000",
    manufactureDate: "2022-12-01",
    serialNumber: "SN789456003",
    location: "Sala 108",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Modem K",
    type: "Fiber Optic",
    model: "MD800",
    manufactureDate: "2023-02-15",
    serialNumber: "SN456789004",
    location: "Sala 109",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Roteador L",
    type: "Wireless",
    model: "RT500",
    manufactureDate: "2023-01-10",
    serialNumber: "SN321654005",
    location: "Sala 110",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Câmera M",
    type: "Security",
    model: "CM600",
    manufactureDate: "2022-08-30",
    serialNumber: "SN987123006",
    location: "Corredor Principal",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Equipamento de Áudio N",
    type: "Audio",
    model: "AU900",
    manufactureDate: "2022-10-10",
    serialNumber: "SN654987007",
    location: "Sala de Conferências",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Impressora O",
    type: "Inkjet",
    model: "IP800",
    manufactureDate: "2023-03-22",
    serialNumber: "SN456789008",
    location: "Sala 111",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
  {
    name: "Armazenamento P",
    type: "NAS",
    model: "ST2000",
    manufactureDate: "2021-05-17",
    serialNumber: "SN123789009",
    location: "Sala de TI",
    imagesUrl: [
      "https://tse3.mm.bing.net/th?id=OIP.IRim9I0CHOFLaFJsxSXeQAHaFj&pid=Api&P=0&h=180",
      "https://crm.ferrotall.com/media/prod_pics_heller/original/3059/mc850_1.png",
    ],
  },
];
